---
openapi: 3.0.2
info:
  title: Camel K - OpenAPI example
  version: 1.0.0
  description: An OpenAPI transformation example with Camel K on OpenShift.
paths:
  /data:
    post:
      requestBody:
        description: Send some data to transform
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataTransformed'
          description: Returns the transformed data
      operationId: create-data-id
      summary: Create data
components:
  schemas:
    Data:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        firstname:
          type: string
          example: Kevin
        lastname:
          type: string
          example: Snow
        shipDate:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        status:
          type: string
          description: Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      required:
        - id
    DataTransformed:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        fullname:
          type: string
          example: Kevin Snow
        shipTimestamp:
          type: integer
          example: 1500658348
        complete:
          type: string
          example: Yes/No
        newField:
          type: string
          description: Random GUID
          example: fd861409-33cb-46db-ba4a-514c557d5141